In [5]:
import yfinance as yf
from pandas_datareader import data as pdr

In [3]:
yf.pdr_override()

In [10]:
data = pdr.get_data_yahoo("AAPL", start="2020-01-01", end="2021-01-01")

[*********************100%%**********************]  1 of 1 completed

In [11]:
data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2020-01-02,74.059998,75.150002,73.797501,75.087502,73.249031,135480400
2020-01-03,74.287498,75.144997,74.125000,74.357498,72.536896,146322800
2020-01-06,73.447502,74.989998,73.187500,74.949997,73.114876,118387200
2020-01-07,74.959999,75.224998,74.370003,74.597504,72.771019,108872000
2020-01-08,74.290001,76.110001,74.290001,75.797501,73.941635,132079200
...,...,...,...,...,...,...
2020-12-24,131.320007,133.460007,131.100006,131.970001,129.850601,54930100
2020-12-28,133.990005,137.339996,133.509995,136.690002,134.494766,124486200
2020-12-29,138.050003,138.789993,134.339996,134.869995,132.704010,121047300
2020-12-30,135.580002,135.990005,133.399994,133.720001,131.572510,96452100
2020-12-31,134.080002,134.740005,131.720001,132.690002,130.559006,99116600